# SPDX-FileCopyrightText: 2024 Aminda Suomalainen <suomalainen+git@mikaela.info>
#
# SPDX-License-Identifier: CC0-1.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.ci for more information
ci:
  autoupdate_schedule: weekly
  skip: [yarn-lint]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"]
        exclude_types: [svg]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-illegal-windows-names
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.6.0"
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
      - id: reuse
  - repo: local
    hooks:
      - id: yarn-lint
        name: linter
        entry: corepack yarn lint
        language: system
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.3
    hooks:
      - id: check-renovate
        additional_dependencies: ["pyjson5"]
